### ISSUE TITLE
Question: Is there a seqkit/split2 equivalent

### ISSUE THREAD

**Issue by tamuanand** [telatin/seqfu2#9]
Hi

First off, thanks a lot for the great tool/utility. 

A question: Is there a utility within seqfu that's similar to seqkit/split2: https://bioinf.shenwei.me/seqkit/usage/#split2

Thanks in advance

**Comment by telatin** [comment]
Hi @tamuanand, thanks for asking!
I personally use both seqfu and seqkit (which is amazing!), and some functionalities were replicated because of slightly different use scenarios or features (most notably I was using `seqkit stats` before making `seqfu stats` with more metrics and - at the time of making it, maybe not now - a bit faster).

Is there something that lack in split2 in your opinion, or that you would like to have a bit faster? In general terms, I am trying to avoid or postpone utilities that will produce multiple files, but maybe in the future this will change :)

**Comment by telatin** [comment]
Hi @tamuanand,
as said previously this is not in the core plans, but as a proof of concept for seqfu-based scripts, now `seqfu>=1.13.1` has a `fu-split` you can tryhttps://telatin.github.io/seqfu2/scripts/fu-split.html

Let me know how it works for you

**Comment by tamuanand** [comment]
Thanks @telatin
